### ISSUE TITLE
JDR_FMT1 : Data format error. The input JPEG data can be collapted.

### ISSUE THREAD

**Issue by AngryTeaPot** [iliasam/STM32_HOST_UVC_Camera#11]
Hello, 
First of all thanks for the UVC it helps a lot.

I worked on YUV2 succesfully but when i turn to MJPEG format i got some error which is like JDR_FMT1 : Data format error. The input JPEG data can be collapted.  Have you met this kind of error before ? if you met , im wondering how you overcome for this stiuation. 

PS: MJPEG is working there is no problem, im getting the frames and displaying on the screen but the images are shaking and corrupted because of the decomp JDR_FMT1  error.

**Comment by iliasam** [comment]
Sorry, I have not meet with a such problem before.

**Comment by AngryTeaPot** [comment]
I solve the Issue. Th problem is about the camera. The camera versions or some brands' cameras may not support the DHT or some specific markers for the MJPEG - JPEG standard. I use Logitech C200 and it fits perfectly for me with the JPEG DHT K.3 standard table.
