### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Mrqinw** [iliasam/STM32_HOST_UVC_Camera#13]
please tell me what is your version of IAR?

**Comment by iliasam** [comment]
IAR 7.50

**Comment by Mrqinw** [comment]
thank you.Can the video of this project be displayed on rgb lcd directly if i dont't connnect the VGA screen?
i have tried this idea,it don't work

**Comment by Mrqinw** [comment]
![image](https://github.com/iliasam/STM32_HOST_UVC_Camera/assets/129501652/537344cc-45f2-477f-ab3a-642df6be9713)

**Comment by iliasam** [comment]
Sorry, I don't understand your question.
Note that "stm32F4_discovery_project" do not need any display, you cant try it first.

**Comment by Mrqinw** [comment]
If I want to display the picture on rgb lcd, what do I need to change?

**Comment by iliasam** [comment]
See https://github.com/iliasam/STM32_HOST_UVC_Camera/blob/master/HAL_source/stm32F429_project/Src/main.c

>  //Draw captured image
      if (USBH_VIDEO_Target_Format == USBH_VIDEO_YUY2)
      {
        lcd_draw_yuyv_picture((uint8_t*)uvc_ready_framebuffer_ptr);
      }
      else
      {
        mjpeg_decompression_and_draw((uint8_t*)uvc_ready_framebuffer_ptr, uvc_ready_frame_length);
      }

And also: https://github.com/iliasam/STM32_HOST_UVC_Camera/blob/master/HAL_source/stm32F429_project/Src/mjpeg_decoding.c#L49
UINT output_func(JDEC* jd, void* bitmap, JRECT* rect)  {}
