### ISSUE TITLE
Need to compile for STM32 Cube IDE

### ISSUE THREAD

**Issue by Ritesh236** [iliasam/STM32_HOST_UVC_Camera#2]
Hello,

I have tried to include and compile for STM32 Cube IDE successfully with some chances into reference example code.

But facing issue like not getting any USB Event even after connecting any USB Camera.

So, Does anyone has tried with STM32 Cube IDE to compile and test it successfully with any USB camera? If yes then let me know

Regards,
Ritesh Prajapati

**Comment by pauleffect90** [comment]
You need to:
1. Make sure the camera works in FS mode.
2. Open up usb ll driver and set the fifo size according to the linked article in description (translate from russian using google). Basically you need to make sure the usb fifo is big enough to accommodate your packets.
