### ISSUE TITLE
How to change the camera resolution?

### ISSUE THREAD

**Issue by liuzhijun23** [iliasam/STM32_HOST_UVC_Camera#6]
I have run the project in STM32F407 success now. I find the camera resolution is 120 X 160，how to change the resolution to 240 X 
 320?

**Comment by iliasam** [comment]
Change UVC_TARGET_WIDTH and UVC_TARGET_HEIGHT to needed values in 
https://github.com/iliasam/STM32_HOST_UVC_Camera/blob/master/HAL_source/Middlewares/ST/STM32_USB_Host_Library/Class/VIDEO/Inc/usbh_video.h

**Comment by liuzhijun23** [comment]
> Change UVC_TARGET_WIDTH and UVC_TARGET_HEIGHT to needed values in
> https://github.com/iliasam/STM32_HOST_UVC_Camera/blob/master/HAL_source/Middlewares/ST/STM32_USB_Host_Library/Class/VIDEO/Inc/usbh_video.h

Thanks,This method works.
